apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  annotations:
    version: "0.2"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      name: blackbox-exporter
      labels:
        app: blackbox-exporter
      annotations:
        prometheus.io/scrape: "pod"
    spec:
      volumes:
      - name: config
        configMap:
          name: be-config
      containers:
      - name: blackbox-exporter
        image: prom/blackbox-exporter
        args:
        - --config.file=/etc/blackbox_exporter/config.yml
        ports:
        - containerPort: 9115
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
