---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana

    spec:
      volumes:
      - name: dashboards
        emptyDir: {}
      - name: config
        configMap:
          name: grafana-config
          items:
          - key: grafana.ini
            path: grafana.ini
          - key: datasources.yml
            path: provisioning/datasources/prometheus.yml
          - key: dashboards.yml
            path: provisioning/dashboards/datascript.yml
      #initContainers:
      #- name: copy-dashboards
      #  image: tomkukral/kubernetes-mixin
      #  command:
      #  - bash 
      #  - -c 
      #  - "cp -v /data/grafana/* /mnt/dashboards/"
      #  volumeMounts:
      #  - name: dashboards
      #    mountPath: /mnt/dashboards
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: config
          mountPath: /etc/grafana
        - name: dashboards
          mountPath: /mnt/dashboards
---
kind: Service
apiVersion: v1
metadata:
  name: grafana
  annotations:
    prometheus.io/scrape: "true"
spec:
  selector:
    app: grafana
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
