alertmanager:
  interval: 60s
  servers:
  - name: local
    uri: http://alertmanager
    timeout: 10s
    proxy: true
    readonly: false
annotations:
  default:
    hidden: false
  hidden:
  - help
  visible: []
debug: true
listen:
  address: "0.0.0.0"
  port: 8080
  prefix: /
log:
  config: false
  level: info
receivers:
ui:
  refresh: 60s
  hideFiltersWhenIdle: true
  colorTitlebar: false
  minimalGroupWidth: 420
  alertsPerGroup: 5
  collapseGroups: collapsedOnMobile
alertAcknowledgement:
  enabled: true
  duration: 60m
authentication:
  header:
    name: X-WEBAUTH-USER
    value_re: ^(.+)$
