groups:
- name: node-exporter
  rules:
  - alert: TargetDown
    expr: "up != 1"
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  - alert: NodeMetricMissing
    expr: |-
      absent(node_cpu_seconds_total) or
      absent(node_memory_SwapFree_bytes) or
      absent(node_memory_MemFree_bytes) or
      absent(node_filesystem_free_bytes)
    for: 10m
    annotations:
      description: Metric (node_cpu_seconds_total) isn't exported

  - alert: NodeCPUUsage
    expr: '(100 - (avg by (instance) (irate(node_cpu_seconds_total{name="node-exporter",mode="idle"}[5m])) * 100)) > 75'
    for: 2m
    annotations:
      description: "{{$labels.instance}}: CPU usage is above 75% (current value is: {{ $value }})"

  - alert: NodeSwapUsage
    expr: '(node_memory_SwapFree_bytest / node_memory_SwapTotal * 100) < 30'
    for: 2m
    annotations:
      description: "{{$labels.instance}}: Swap usage is hight (remaining: {{ $value }}%)"

  - alert: NodeMemoryUsage
    expr: '(node_memory_MemFree_bytes / node_memory_MemTotal_bytes * 100) < 25'
    for: 2m
    annotations:
      description: "{{$labels.instance}}: Memory usage is high (remaining: {{ $value }}%)"

  - alert: NodeDiskFull
    expr: predict_linear(node_filesystem_free_bytes[6h], 3600 * 24 * 3) < 0
    for: 30m
    annotations:
      description: device {{$labels.device}} on node {{$labels.instance}} is running full within the next 3 days (mounted at {{$labels.mountpoint}})
