apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argo
  labels:
    cluster: c3
    app: argo-workflows
spec:
  project: default
  source:
    repoURL: https://github.com/tbecicka/argocd.git
    targetRevision: HEAD
    path: argo/workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    