apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kad
  namespace: argo
spec:
  destination:
    namespace: kad
    server: https://kubernetes.default.svc
  project: default
  source:
    path: helm
    repoURL: https://gitlab.com/6shore.net/kad.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    
