apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argo
  labels:
    app: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tbecicka/argocd.git
    targetRevision: HEAD
    path: loki
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
