apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argo
  labels:
    cluster: c3
    app: minio
spec:
  project: default
  source:
    repoURL: https://github.com/tbecicka/argocd.git
    targetRevision: HEAD
    path: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    