namespace: minio
commonLabels:
  app: minio
resources:
- namespace.yml
- pvc.yml
- ingress.yml
- deploy.yml
patchesStrategicMerge:
- patch_deploy.yml


secretGenerator:
- name: minio
  literals:
  - accesskey=glass
  - secretkey=paper123
